.all-contributorsrc
README.md
src/app/zippy/zippy.component.spec.ts
src/app/zippy/zippy.component.ts
src/lib/src/dispatch-events.ts
src/lib/src/event-objects.ts
src/lib/src/internals.ts

This PR fixes #9 (at least partially)

Fix `dispatchKeyboardEvent' not working (#9)

---

projects/spectator/src/lib/matchers-types.d.ts

fixes https://github.com/NetanelBasal/spectator/issues/51

fix(types): add types to matchers definitions

---

README.md

docs(readme): fixed typo

---

projects/spectator/src/lib/event-objects.ts

This attempts to fix issue #78. I don't see any unit tests that i can update to make sure the fix is correct?

Fix keyboard event creation.

---

projects/spectator/src/lib/errors.ts
projects/spectator/src/lib/internals.ts
src/app/zippy/zippy.component.jest.ts
src/app/zippy/zippy.component.spec.ts
src/app/zippy/zippy.component.ts

Solves https://github.com/NetanelBasal/spectator/issues/85

Prevent error when component is not found By.directive

---

projects/spectator/src/lib/mock.ts
src/app/mocks.spec.ts
src/app/widget.service.ts

Fixes https://github.com/NetanelBasal/spectator/issues/93

Stop mockProvider to modify its input

---

projects/spectator/jest/src/matchers-types.d.ts
projects/spectator/src/lib/matchers-types.d.ts
src/app/zippy/zippy.component.jest.ts
src/app/zippy/zippy.component.spec.ts

feat(spectator): mark toHaveAttribute second parameter as optional

---

projects/spectator/src/lib/mock.ts
src/app/spy-object/person.ts
src/app/spy-object/spy-object.jest.ts
src/app/spy-object/spy-object.spec.ts

This PR adds the following features to `SpyObject<T>`:
* Clones the original getters/setters (so that you could spy on them if you want)
* Allowing to assign public properties, which was not possible due to incorrect type definitions
* Allowing to assign readonly properties (with additional cast method)
I added relevant unit tests for these features.
```typescript
class Person {
public readonly name: string = 'Some name';
public birthYear: number = 1990;
public sayHi(): string {
return 'Hi!';
}
public get age(): number {
return 2019 - this.birthYear;
}
}
```
```typescript
const person = createSpyObject<Person>;
person.birthYear = 1990; // Error: Type 1990 is not assignable to type 'number & CompatibleSpy'
spyOnProperty(person, 'age', 'get'); // error: object has no property 'age' …
```

feat(mock): writable properties for SpyObjects

---

projects/spectator/src/lib/host.ts
projects/spectator/src/lib/internals.ts
src/app/view-children/view-children.component.jest.ts
src/app/view-children/view-children.component.spec.ts

Proposal for https://github.com/NetanelBasal/spectator/issues/142.

feat(spectator): additional query capabilities

---

projects/spectator/src/lib/spectator-service/create-factory.ts
projects/spectator/test/ng-on-destroy.service.spec.ts
projects/spectator/test/ng-on-destroy.service.ts

fixes https://github.com/ngneat/spectator/issues/92
Rebased version of https://github.com/ngneat/spectator/pull/95.
Credits to @MartinNuc

feat(service): call OnDestroy lifecycle on service after each test

---

projects/spectator/src/lib/spectator-host/spectator-host.ts
projects/spectator/src/lib/spectator/spectator.ts

```
[X] Bugfix
[ ] Feature
```
Changed `spectator.element` from `Element` to `HTMLElement` so that you don't need to cast it yourself.

fix(spectator): fix incorrect element typing

---

README.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs: fix wrong method name

---

README.md

```
[ ] Bugfix
[ ] Feature
```
No recommendation to mock components
Recommend to use [ng-mocks](https://github.com/ike18t/ng-mocks) 
```
[ ] Yes
[x] No
```

docs: mock components with ng-mocks

---

projects/spectator/schematics/src/spectator/index.ts

Fixes #256
```
[x] Bugfix
[ ] Feature
```
See issue #256
Fixes the bug described in #256.
```
[ ] Yes
[x] No
```
n/a

fix(schematics): handle the path provided with the name

---

projects/spectator/package.json

```
[x] Bugfix
[ ] Feature
```
Spectator 5.7.0 released with a jQuery 3.4.1 dependency which has a security vulnerability.
This is due to an incomplete fix by #300 which only updated the root package.json
This PR updates the package.json that is used for release to fix the vulnerability.
```
[ ] Yes
[x] No
```

fix(spectator): update jquery to 3.5.0

---

README.md

- [ x] The commit message follows our guidelines: https://github.com/ngneat/spectator/blob/master/CONTRIBUTING.md#commit
- [ x] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
[ x] Documentation content changes
```
```
[ ] Yes
[ x] No
```

docs: fix typo http example

---

projects/spectator/src/lib/matchers.ts

Fix typing mismatch with @types/jasmine.

---

projects/spectator/src/lib/internals/event-objects.ts

Fix for "cannot redefine property: defaultPrevented" (#340).

---

docs/docusaurus.config.js

```
[ ] Bugfix
[ ] Feature
```
Link is broken
Link works
```
[ ] Yes
[x] No
```

docs: ✏️ fix GitHub link typo

---

projects/spectator/jest/src/lib/dom-selectors.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(selectors): forgot to expose byrole selector

---

README.md
projects/spectator/jest/src/lib/matchers-types.ts
projects/spectator/jest/test/matchers/matchers.spec.ts
projects/spectator/src/lib/matchers-types.ts
projects/spectator/src/lib/matchers.ts
projects/spectator/test/matchers/matcher-enhancements.component.spec.ts

```
[x] Bugfix
[x] Feature
```
This is a proposal to add additional support for the following by passing an optional config object: https://github.com/ngneat/spectator/issues/361
```
[] Yes
[x ] No
```

Feature/fix: toHaveClass should accept classes in any order if configured

---

.vscode/settings.json
README.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

doc(sample-repo): added spectator & jest sample repo reference

---

README.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

Fix incorrect method reference

---

projects/spectator/schematics/src/spectator/files/directive/__name@dasherize__.directive.spec.ts

`describe('MyDirective ', () => {})` to `describe('MyDirective', () => {})`
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
fix typo
```
[ ] Yes
[x] No
```

Remove unnecessary space in the describe title

---

CHANGELOG.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs: fix typo in changelog

---

README.md

refs #533
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #533
```
[ ] Yes
[x] No
```

docs: add section about mocked dependencies used in the constructor

---

projects/spectator/test/matchers/matcher-enhancements.component.spec.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
mulitple -> multiple

Fix typo in matcher-enhancements.component.spec.ts

---

docs/docs/testing-services.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix: typo on testing services page

---

docs/docs/mocking-components.md

A comprehensive example how to use `ng-mocks`: `MockBuilder(ThingToTest, ItsModule)` or `MockBuilder(StandaloneComponent)`.
Related PR in ng-mocks: https://github.com/ike18t/ng-mocks/pull/2922
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs: ng-mocks example for standalone components

---

README.md

```
[ ] Bugfix
[ ] Feature
```

Add missing import in README

---

docs/docs/testing-with-http.md

fix method name in http service example
```
[ ] Bugfix
[ ] Feature
```
Incorrect method `getTodos` used on the last sample test in example.
Example uses now correct method `collectTodos`. 
```
[ ] Yes
[x] No
```

docs(testing-with-http): fix method name in http service example

---

README.md
docs/docs/queries.md
projects/spectator/jest/test/dom-selectors/dom-selectors.component.spec.ts
projects/spectator/src/lib/base/dom-spectator.ts
projects/spectator/src/lib/types.ts
projects/spectator/test/app.component.ts
projects/spectator/test/app.module.ts
projects/spectator/test/dom-selectors/dom-selectors.component.spec.ts
projects/spectator/test/dom-selectors/dom-selectors.component.ts

```
[ ] Bugfix
[x] Feature
```
Issue Number: #525

feat(query): allow to specify within parameter

---

projects/spectator/src/lib/spectator-routing/create-factory.ts

```
[X] Bugfix
[ ] Feature
```
Issue Number: 592
```
[ ] Yes
[X] No
```
This is the issue: https://github.com/ngneat/spectator/issues/592

fix(#592): createRoutingFactory issue overriding standalone components, directives or pipes

---

projects/spectator/jest/src/lib/mock.ts

fixes mocked types with jest
✅ Closes: #614
```
[x] Bugfix
[ ] Feature
```
TypeScript error with jest:
Issue Number: #614 
No TypeScript errors with jest:
```
[ ] Yes
[x] No
```

fix: 🐛 jest SpyObject mock

---

projects/spectator/package.json
yarn.lock

✅ Closes: #676
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: upgrade to `jquery@^3.7.1`
```
x
x
```
[ ] Yes
[x] No
```
Updated to `jquery@^3.7.1` with caret (`^`), to include future minor and patch versions of jQuery

chore: 🤖 upgrade jquery to v3.7.1

---

README.md

Update build status badge from travis-ci to github-actions
```
[ ] Bugfix
[ ] Feature
```
Broken travis-ci build status badge
GitHub Actions build status badge
```
[ ] Yes
[x] No
```

docs: ✏️ fix broken build status badge

---

projects/spectator/src/lib/mock.ts

- [X ] The commit message follows our guidelines: https://github.com/ngneat/spectator/blob/master/CONTRIBUTING.md#commit
```
[ X] Bugfix
[ ] Feature
```
#707 get merged with some failing tests. 
They didn't initially fail on my box, but I saw the failures post merge in the checks and managed to reproduce them on my box. 
The tests pass now :)
```
[ ] Yes
[X ] No
```

fix: regression caused by strong typings change
