- src/lib/src/index.ts
- src/lib/src/mock-directive.ts
Thanks for the library, it's a great way of making my unit tests more concise! However I encountered some problems when trying to mock directives. I couldn't mock them with `MockComponent` because they were being applied to an element that already had a component registered on it. So this commit adds a `MockDirective` class that is exactly symmetrical to `MockComponent`.
> feat(directive): add MockDirective helper function

- package-lock.json
- package.json
Unit tests currently fail locally because the root project is missing jQuery, and the version previously stored in the library's node_modules has been removed.
> fix(dev): add missing jQuery dependency

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/dom-selectors/dom-selectors.component.spec.ts
- src/app/dom-selectors/dom-selectors.component.ts
- src/lib/package-lock.json
- src/lib/package.json
- src/lib/src/dom-selectors.ts
- src/lib/src/host.ts
- src/lib/src/index.ts
- src/lib/src/internals.ts
This PR allows you to use selectors based on dom-testing-library in `query`, `queryHost` and `queryAll` methods. An example of the usage is included in the demo app.
```html
<input type="text" placeholder="By placeholder" id="by-placeholder-input">
```
```typescript
it("should allow querying by placeholder", () => {
const element = spectator.query(byPlaceholder("By placeholder"));
expect(element).toHaveId("by-placeholder-input");
});
```
Note that this uses `dom-testing-library` v2.1.0 because it is the last version before typings were introduced for TypeScript. These typings use the `infer` keyword which will throw a compile error on anything below TypeScript 2.8, which Angular does not currently support. When Angular is updated to support TS2.8 we can update `dom-testing-library`.
Some …
> feat(query): add dom-testing-library query tools

- src/lib/src/mock-component.ts
This changes the default template for `MockComponent` from `''` to `'<ng-content></ng-content>'`, so that the content of mocked components are projected by default. Usually you want to test the projected contents as well, because they are part of their host component.
> feat(mock-component): content projection for default MockComponent

- src/lib/src/matchers.ts
Fix description for `toHaveAttribute` matcher. Add description for `toHaveProperty` matcher.
> docs(matchers): fix recent matcher descriptions

- src/app/app.module.ts
- src/app/no-overwritten-providers/dummy.service.ts
- src/app/no-overwritten-providers/no-overwritten-providers.component.spec.ts
- src/app/no-overwritten-providers/no-overwritten-providers.component.ts
- src/lib/src/config.ts
- src/lib/src/host.ts
- src/lib/src/spectator.ts
Since commit https://github.com/NetanelBasal/spectator/commit/ef84b1679f4bf1a7f9cb6de46c4f30cfcb14c1ec, it is required to set componentProviders even if I'm not mocking anything in the component scope.
What I suggest is not to need to declare componentProviders in case I do not mock anything.
Before you could not inject DumyService unless you declare it in componentProviders as well
> fix(host): componentProviders should not always be overwritten

- projects/spectator/src/lib/mock-component.ts
> docs(mock-component): deprecate MockComponent

- .all-contributorsrc
- README.md
- src/app/async-input/async-input.component.jest.ts
- src/app/async/async.component.jest.ts
- src/app/button/button.component.jest.ts
- src/app/calc/calc.component.jest.ts
- src/app/consum-dynamic/consume-dynamic.component.jest.ts
- src/app/consumer.service.jest.ts
- src/app/dom-selectors/dom-selectors.component.jest.ts
- src/app/fg/fg.component.jest.ts
- src/app/form-input/form-input.component.jest.ts
- src/app/hello/hello.component.jest.ts
- src/app/no-overwritten-providers/no-overwritten-providers.component.jest.ts
- src/app/unless/unless.component.jest.ts
- src/app/view-children/view-children.component.jest.ts
- src/app/widget/widget.component.jest.ts
Add Jest specs to exercise as much of the API as the Jasmine specs do.
I discovered that the DOM selectors have not been exposed in Spectator's Jest API.
> test(jest): add Jest specs matching all the Jasmine specs that have Spectator imports

- projects/spectator/jest/src/matchers-types.d.ts
- projects/spectator/jest/src/public_api.ts
- projects/spectator/tsconfig.lib.json
- projects/spectator/typings/jest/index.d.ts
Closes https://github.com/NetanelBasal/spectator/issues/63. Tested on an initial Angular CLI project with Jasmine, and on an existing project with Jest.
> fix(jest): fix type collisions between jasmine/jest

- projects/spectator/src/lib/internals.ts
- src/app/unless/unless.component.jest.ts
- src/app/unless/unless.component.spec.ts
This solves https://github.com/NetanelBasal/spectator/issues/66 where `query` would fail for a directive because it doesn't have a `debugElement`.
Fix is to use `hostDebugElement` when `debugElement` is not set.
> Make queries work for directives

- projects/spectator/src/lib/http.ts
This implements workaround for https://github.com/NetanelBasal/spectator/issues/75
To see that error message I had to use newer version of karma/jasmine/karma-jasmine-html-reporter. After this change the message is no longer there.
> Avoid spec has no expectations when using expectOne

- projects/spectator/src/lib/config.ts
- src/app/app.module.ts
- src/app/integration/integration-child.component.ts
- src/app/integration/integration-parent.component.spec.ts
- src/app/integration/integration-parent.component.ts
- src/app/integration/integration.module.ts
I suggest to introduce a `declareComponent` option to the SpectatorOptions, usecase would be if the component i want to test is already declared in a module together with it's dependecies. This benefits the reusability of already existing modules and simplifies setting up tests for components. Example:
```
@NgModule({
declarations:[TheComponent, SubComponent],
exports:[TheComponent],
imports: [SomeModule, AnotherModule]
})
export class TheComponentModule {}
```
With `declareComponent` option:
```
const createHost = createHostComponentFactory({
component: TheComponent,
imports: [TheComponentModule],
declareComponent: false
});
```
Without `declareComponent` option:
```
const createHost = createHostComponentFactory({
component: TheComponent,
declarations:[SubComponent],
imports: …
```
> feat(config): add declareComponent option

- projects/spectator/src/lib/mock.ts
- src/app/consumer.service.jest.ts
- src/app/consumer.service.spec.ts
- src/app/consumer.service.ts
- src/app/provider.service.ts
Fixes https://github.com/NetanelBasal/spectator/issues/88
> Allow mockProvider to mock methods using 2nd argument

- projects/spectator/src/lib/config.ts
This allows to make unit tests for Angular components with web components, for which you might want to use `CUSTOM_ELEMENTS_SCHEMA` (instead of `NO_ERRORS_SCHEMA`).
> fix(config): map schemas option to initial module config

- projects/spectator/jest/src/mock.ts
- projects/spectator/package.json
Just upgraded to Jest 24, and got compiler errors. I think the reason this bug was nog blocking before, is that `@types/jest@24.0.0` is more strict with generics.
**The issue**
Given an interface:
```typescript
interface Person {
name: string;
saySomething: () => string;
}
```
when you define `SpyObject<Person>` as `{ [P in keyof Person]: Person[P] & jest.Mock<Person>`, then `personSpyObject.saySomething` would be a `() => string & jest.Mock<Person>`. That is wrong, because it should be a `jest.Mock<string>`.
To get the return type of `Person[P]` I use `ReturnType` combined with conditional types from Typescript 2.8. Awesome stuff by the way.
> fix(jest): fix for incorrect typing of SpyObject for Jest

- projects/spectator/jest/src/matchers-types.d.ts
- projects/spectator/src/lib/matchers-types.d.ts
- projects/spectator/src/lib/matchers.ts
- src/app/hello/hello.component.jest.ts
- src/app/hello/hello.component.spec.ts
During our daily work, we discovered that the toHaveText matcher is not accurate for exact matches. For instance, you can have this line of code:
`expect('foo').toHaveText('bar'); // true`
This is true, of course. However, this is true as well:
`expect('foo').toHaveText(''); // true`
`expect('foo').toHaveText('ar'); // true`
In order to have an exact text matcher, I have added the toHaveExactText matcher. It works as follows:
`expect('foo').toHaveExactText('bar'); // true`
`expect('foo').toHaveExactText('ar'); // false`
Furthermore, one can call the exact matcher by adding an additional property to the original matcher as well:
`expect('foo').toHaveText('ar', false); // true`
`expect('foo').toHaveText('ar', true); // false`
What do you guys think of this? Please, feel free to change the …
> Add exact text matcher support

- package-lock.json
- package.json
Bumped version of jQuery to 3.4.1, to avoid auditing tools from emitted
vulnerability warnings.
Fixes #107
> fix: jQuery version bump

- projects/spectator/src/lib/matchers.ts
I recreated the visibility check to be jsdom friendly to make them work with Jest too.
Mixes jQuery 1 and 3 :visible and :hidden pseudo-selector implementation, because jQuery 3 implementation won't work in jsdom: layout isn't managed.
Also checks for 'hidden' attribute.
(I accidentally closed previous PR while force pushing an update)
Fixes #97
> fix(matchers): visibility matchers work with Jest

- README.md
Update All Contributors links. They moved from being a Kent C. Dodds project to a self-contained repository and website.
> docs: update All Contributors links

- projects/spectator/src/lib/matchers.ts
Ensures the matcher logic operates on an element even if a selector is provided as input to the function.
> fix(matchers): pass input to `isHidden` through jQuery (fixes #122)

- projects/spectator/jest/src/service.ts
- projects/spectator/src/lib/config.ts
- projects/spectator/src/lib/host.ts
- projects/spectator/src/lib/internals.ts
- projects/spectator/src/lib/service.ts
- src/app/async/async.component.jest.ts
- src/app/async/async.component.spec.ts
- src/app/auth.service.jest.ts
- src/app/auth.service.spec.ts
- src/app/auto-focus.directive.jest.ts
- src/app/auto-focus.directive.spec.ts
- src/app/button/button.component.jest.ts
- src/app/button/button.component.spec.ts
- src/app/consumer.service.jest.ts
- src/app/consumer.service.spec.ts
- src/app/form-input/form-input.component.jest.ts
- src/app/todos-data.service.jest.ts
- src/app/todos-data.service.spec.ts
- src/app/view-children/view-children.component.jest.ts
- src/app/view-children/view-children.component.spec.ts
- src/app/widget/widget.component.jest.ts
- src/app/zippy/zippy.component.jest.ts
- src/app/zippy/zippy.component.spec.ts
This PR improves type inference for the following methods:
* `SpectatorService.get`
* `SpectatorWithHost.getDirectiveInstance`
* `Spectator.query`
* `Spectator.queryAll`
* `Spectator.queryLast`
Before:
```typescript
const fooService = spectatorService.get<FooService>(FooService);
const fooDirective = host.getDirectiveInstance<FooDirective>(FooDirective);
const barDirective = spectator.query<BarDirective>(BarDirective);
const bazDirectives = spectator.queryAll<BazDirective>(BazDirective);
const someElementRef = spectator.query<ElementRef>(BarDirective, { read: ElementRef });
```
Now, you can omit the generic type and profit from type inference:
```typescript
const fooService = spectatorService.get(FooService);
const fooDirective = host.getDirectiveInstance(FooDirective);
const barDirective …
```
> fix(spectator): improve type inference for Spectator

- projects/spectator/jest/src/host.ts
- projects/spectator/jest/src/internals.ts
- projects/spectator/jest/src/service.ts
- projects/spectator/src/lib/host.ts
- projects/spectator/src/lib/http.ts
- projects/spectator/src/lib/index.ts
- projects/spectator/src/lib/internals.ts
- projects/spectator/src/lib/service.ts
- projects/spectator/src/lib/token.ts
- src/app/injection-tokens.jest.ts
- src/app/injection-tokens.spec.ts
- src/app/query.service.ts
This PR is an improvement of https://github.com/NetanelBasal/spectator/pull/133.
What has been changed:
* Use `Token<T>` instead of `Type<T>`, which allows to use abstract classes as DI token (thanks to @dscheerens). It still allows you to specify a more specific generic type. Added unit tests for this.
* Improve type inference for `SpectatorWithHost.queryHost` and `SpectatorWithHost.queryHostAll` as well
> fix(spectator): improve type inference even more

- CHANGELOG.md
- package.json
This PR adds `standard-version` configuration to make releasing easier and to maintain a conventional changelog.
* I removed the version of the root package.json
* The standard version will be ran from `projects/spectator` directory so that the version bump will affect the published package.json
* I added the build step as `postbump` life-cycle hook
* I generated an initial changelog for the existing releases
Releasing is now as simple as `npm run release`. Afterwards, you will only need to run `git push --follow-tags origin master && npm publish dist/spectator`  (note the dist/spectator directory here).
Closes https://github.com/NetanelBasal/spectator/issues/136 and closes https://github.com/NetanelBasal/spectator/issues/141.
> build: standard-version setup and initial changelog

- projects/spectator/src/lib/mock.ts
- src/app/spy-object/spy-object.jest.ts
- src/app/spy-object/spy-object.spec.ts
So I did a small test to check breaking changes in v4. Turns out the only issue for on of our projects was a regression introduced in 3.11.1 :smile: in this change: https://github.com/NetanelBasal/spectator/commit/977059a0e7e89017f6ddd775b0fbacf46fdedc66. 
This PR improves that change by:
* using a null return instead of the real descriptor. The real descriptor may need to access stuff that does not exists on the mock object, so it makes no sense to use that one.
* it skips properties that may already exist due to custom decorators
* it skips setters (no reason to mock them explicitly)
This fix still enables you to spy on a property, which was the reason to add it in the first place.
> fix(mock): fix regression caused by mocked properties

- projects/spectator/src/lib/internals.ts
- src/app/auto-focus.directive.jest.ts
- src/app/auto-focus.directive.spec.ts
Closes https://github.com/NetanelBasal/spectator/issues/153.
This makes it easier to target the component element, e.g. for testing directives:
Before:
```ts
spectator.click(spectator.element);
spectator.typeInElement('foo', spectator.element);
```
After:
```ts
spectator.click();
spectator.typeInElement('foo');
```
> feat(spectator): use spectator element as default selector

- README.md
- projects/spectator/jest/src/lib/spectator-for-directive.ts
- projects/spectator/jest/src/public_api.ts
- projects/spectator/jest/test/auto-focus.directive.spec.ts
- projects/spectator/jest/test/highlight.directive.spec.ts
- projects/spectator/src/lib/base/dom-spectator.ts
- projects/spectator/src/lib/internals/query.ts
- projects/spectator/src/lib/spectator-for-directive/create-factory.ts
- projects/spectator/src/lib/spectator-for-directive/initial-module.ts
- projects/spectator/src/lib/spectator-for-directive/options.ts
- projects/spectator/src/lib/spectator-for-directive/spectator-for-directive.ts
- projects/spectator/src/lib/spectator-with-host/create-factory.ts
- projects/spectator/src/lib/spectator-with-host/spectator-with-host.ts
- projects/spectator/src/lib/spectator-with-routing/create-factory.ts
- projects/spectator/src/lib/spectator/create-factory.ts
- projects/spectator/src/lib/spectator/spectator.ts
- projects/spectator/src/public_api.ts
- projects/spectator/test/auto-focus.directive.spec.ts
So what I basically did:
- Moved stuff from `Spectator` to abstract `DomSpectator` (for querying, event dispatching, etc) in order to reuse it
- Created new `SpectatorForDirective` which contains stuff from both `Spectator` and `SpectatorWithHost`
- it uses the host fixture, so that querying etc is done from host
- instead of `component` this one has a `directive` instance
- existing code still works (I kept the unit tests)
- added some tests for the new factory (we should have more of them I think)
- updated README
> feat: add factory for SpectatorForDirective

- vscode-snippets/package.json
This enables the use of the code snippets within Typescript files.
> fix(vscode-snippets): change snippet language

- projects/spectator/src/lib/base/dom-spectator.ts
```
[x] Bugfix
[ ] Feature
```
Changed `spectator.queryLast` from `Element[]` to `Element`, because `queryLast` should return only one value.
```
[ ] Yes
[x] No
```
> fix(spectator): fix incorrect method typing

- README.md
- projects/spectator/jest/src/lib/mock.ts
- projects/spectator/jest/test/with-routing/my-page.component.spec.ts
- projects/spectator/src/lib/mock.ts
- projects/spectator/src/lib/spectator-routing/create-factory.ts
- projects/spectator/src/lib/spectator-routing/initial-module.ts
- projects/spectator/src/lib/spectator-routing/options.ts
- projects/spectator/src/lib/spectator-routing/router-stub.ts
- projects/spectator/src/lib/spectator-routing/spectator-routing.ts
- projects/spectator/test/with-routing/my-page.component.spec.ts
- projects/spectator/test/with-routing/my-page.component.ts
Closes https://github.com/ngneat/spectator/issues/179.
```
[ ] Bugfix
[X] Feature
```
The `ActivatedRouteStub` does not work well with `RouterTestingModule` and `Location`.
Issue Number: 179
This PR provides a feature toggle. Example in README.
```
[ ] Yes
[X] No
```
> feat(routing): add option to disable stubs and use RouterTestingModule

- projects/spectator/jest/src/lib/mock.ts
- projects/spectator/jest/test/mock.spec.ts
Fix bug causing the template object to mutate when creating spy object for jest (Related to #94)
```
[x] Bugfix
[ ] Feature
```
> fix(jest/lib): template mutation with createSpyObject

- README.md
- projects/spectator/src/lib/base/dom-spectator.ts
- projects/spectator/src/lib/matchers-types.d.ts
- projects/spectator/src/lib/matchers.ts
- projects/spectator/src/lib/select-option.ts
- projects/spectator/src/lib/types.ts
- projects/spectator/test/form-select/form-select.component.spec.ts
- projects/spectator/test/form-select/form-select.component.ts
- [x ] The commit message follows our guidelines: https://github.com/ngneat/spectator/blob/master/CONTRIBUTING.md#commit
- [x ] Tests for the changes have been added (for bug fixes / features)
- [x ] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[x ] Feature
```
Issue Number: [225](https://github.com/ngneat/spectator/issues/225)
Can now pass an `HTMLOptionElement` or an array of `HTMLOptionElement`s as the `options` parameter in …
> feat: selectOption accepts HTMLOptionElements

- README.md
- [ x ] The commit message follows our guidelines: https://github.com/ngneat/spectator/blob/master/CONTRIBUTING.md#commit
```
[ ] Bugfix
[ ] Feature
[ x ] Documentation content changes
```
Add documentation on how to test components which are included in a module specific to that component. Its not necessary then to define the imports list again and instead use the module as it is.
It took me some time check the code if it is possible at all to avoide the described error and, thus, I found the property …
> docs: add info on SCAM and declareComponent usage

- README.md
- projects/spectator/jest/src/lib/matchers-types.d.ts
- projects/spectator/src/lib/matchers-types.d.ts
- projects/spectator/src/lib/matchers.ts
- projects/spectator/src/lib/types.ts
- projects/spectator/test/matcher-enhancements/matcher-enhancements.component.spec.ts
- projects/spectator/test/matcher-enhancements/matcher-enhancements.component.ts
Add additional custom matchers to the API
close #217
```
[ ] Bugfix
[x] Feature
```
```ts
expect('.zippy').toHaveClass('class a, class b');
expect('some option').toHaveText('Content 1, Content 2, Content 3');
expect('some input').toHaveValue('value 1, value 2, value 3');
expect('.zippy').toHaveAttribute('id', 'zippy');
expect('.zippy').toHaveAttribute('name', 'zippy');
expect('img').toHaveProperty('src', 'http://localhost:9876/assset/toto.png'); …
```
> feat(matchers): add more custom matchers to the API #217

- projects/spectator/src/lib/spectator-host/spectator-host.ts
* all tests passed and this is just a type definition change, so I didn't see a need
* looked through the docs didn't see anything related to type information around queryHostAll
```
[ ] Bugfix
[ ] Feature
[ x] Other... Please describe:
```
A change to the type definition of queryHostAll.
https://github.com/ngneat/spectator/issues/230
Issue Number: 230
I changed the type of queryHostAll from <R extends Element[]> to <R extends Element>.
```
[ ] Yes
[ ] No
```
🤷‍♂ 
I would assume a change to a type …
> fix(spectator): fix for incorrect type definition on queryHostAll (#230)

- README.md
- projects/spectator/src/lib/http.ts
- projects/spectator/src/lib/spectator-http/spectator-http.ts
- projects/spectator/test/todos-data.service.spec.ts
- projects/spectator/test/todos-data.service.ts
An addition to the SpectatorHttp API.
```
[ ] Bugfix
[x] Feature
```
`spectator.expectOne()` calls `this.controller.verify()` which causes tests to fail if there are concurrent requests going out.
Issue Number: 231
Adding `spectator.expectConcurrent()` allows for expecting multiple requests.
```
[ ] Yes
[x] No
```
>  feat(spectator): added expectConcurrent to spectator-http (#231)

- README.md
- projects/spectator/src/lib/spectator-directive/create-factory.ts
- projects/spectator/src/lib/spectator-directive/options.ts
- projects/spectator/test/directive-providers.directive.spec.ts
- projects/spectator/test/directive-providers.directive.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #236 
Now it is possible to override the directive providers with mocks or with own providers.
```
[ ] Yes
[x] No
```
> feat(spectator): added directiveProviders to spectator-directive (#236)

- README.md
- projects/spectator/src/lib/internals/event-objects.ts
- projects/spectator/src/lib/internals/key-parser.ts
- projects/spectator/src/lib/types.ts
- projects/spectator/test/events/events.component.html
- projects/spectator/test/events/events.component.spec.ts
- projects/spectator/test/events/events.component.ts
This commit adds support to spectator.keyboard.pressKey() for triggering
key events with modifier keys.
Example, spectator.keyboard.pressKey('ctrl.shift.a').
```
[ ] Bugfix
[x] Feature
```
Right now, `spectator.keyboard.pressKey()` does not support key events with key modifiers (meta, ctrl, alt, shift). `spectator.keyboard.pressKey('ctrl.a')` would produce an error.
Issue Number: 241
With this PR, `spectator.keyboard.pressKey('ctrl.a')` will produce a key event that …
> feat: added modifier key support to keyboard api (#241)

- README.md
- projects/spectator/schematics/src/spectator/component-schema.json
- projects/spectator/schematics/src/spectator/directive-schema.json
- projects/spectator/schematics/src/spectator/files/component-custom-host/__name@dasherize__.component.spec.ts
- projects/spectator/schematics/src/spectator/files/component-host/__name@dasherize__.component.spec.ts
- projects/spectator/schematics/src/spectator/files/component/__name@dasherize__.component.spec.ts
- projects/spectator/schematics/src/spectator/files/directive/__name@dasherize__.directive.spec.ts
- projects/spectator/schematics/src/spectator/schema.js.map
- projects/spectator/schematics/src/spectator/schema.ts
- projects/spectator/schematics/src/spectator/service-schema.json
Specifying the --jest flag imports from `@ngneat/spectator/jest`
```
[ ] Bugfix
[x] Feature
```
If you want to use the Jest enabled imports you have to manually update the import path
If you supply the `--jest` flag the Jest enabled import path will automatically be applied.
```
[ ] Yes
[x] No
```
> feat(schematics): add --jest flag

- README.md
- projects/spectator/src/lib/base/dom-spectator.ts
- projects/spectator/src/lib/types.ts
- projects/spectator/test/app.module.ts
- projects/spectator/test/child-custom-event/child-custom-event-parent.component.spec.ts
- projects/spectator/test/child-custom-event/child-custom-event-parent.component.ts
- projects/spectator/test/child-custom-event/child-custom-event.component.ts
- projects/spectator/test/child-custom-event/child-custom-event.module.ts
```
[ ] Bugfix
[X] Feature
```
Issue Number: https://github.com/ngneat/spectator/issues/249
Add a new `triggerEventHandler ` method directly to spectator object.
Basically a helper on top of `debugElement.triggerEventHandler`, with type check output name/value when using component/directive symbol, and call detectChange.
Also support string selector in case you don't have access to the symbol.
(Don't know if this works with web component).
```
[ ] Yes
[X] No
```
Not …
> feat: 🎸 Add triggerEventHandler method (#249)

- package-lock.json
- projects/spectator/jest/src/lib/matchers-types.d.ts
- projects/spectator/jest/test/form-select/form-select.component.spec.ts
- projects/spectator/jest/test/form-select/form-select.component.ts
- [X ] The commit message follows our guidelines: https://github.com/ngneat/spectator/blob/master/CONTRIBUTING.md#commit
- [X ] Tests for the changes have been added (for bug fixes / features)
- [X ] Docs have been added / updated (for bug fixes / features)
```
[X ] Bugfix
[ ] Feature
```
When using `toHaveSelectedOptionsMatcher` with Jest, tests fail with the error `Property 'toHaveSelectedOptions' does not exist on type …
> fix(matchers): 🐛 add toHaveSelectedOptions matcher for jest

- projects/spectator/src/lib/base/dom-spectator.ts
- projects/spectator/test/zippy/zippy.component.spec.ts
- projects/spectator/test/zippy/zippy.component.ts
```
[ ] Bugfix
[x] Feature
```
You can use DOMSpectator methods `query()`, `queryAll()` and `queryLast()` with param `root: true` to get HTML element finding it in `document`.
But it works ONLY for string selectors (like `<title>` or `.some-class` etc.).
I've got cases and there is would be great to have the possibility to pass selector which are instances of `DOMSelector` class (like `byText`, `byAltText` etc., custom DOMSelector selectors).
Issue Number: #273 
Works …
> feat(dom-spectator): add elem query with root opt for DOMSelector (#273)

- projects/spectator/schematics/src/spectator/files/service/__name@dasherize__.service.spec.ts
Add missing condition to load factory and service from jest module.
```
[X] Bugfix
[ ] Feature
```
Generating service for jest doesn't import from Jest module.
Issue Number: 272
Import from the appropriate module
```
[ ] Yes
[X] No
```
I had to bypass the precommit hooks as prettier doesn't accept the schematics syntax in the import
> fix: schematics service for jest

- projects/spectator/src/lib/matchers.ts
- projects/spectator/test/hello/hello.component.spec.ts
- projects/spectator/test/hello/hello.component.ts
Used .css() method from JQuery are using .getComputedStyles(element) in core but it's not always passing in testing with jest though styles are applied directly to element and also are existing in .getComputedStyles(element) result in browser.
So need to fail tests in toHaveStyle matcher only if both JQuery .css() and HTMLElement.style objects don't contain specified property with specified value
```
[x] Bugfix
[ ] Feature
```
Issue Number: #270 
Working as expected, …
> fix(mathers): fix passing toHaveStyle if styles applied in attr (#270)

- projects/spectator/package.json
- projects/spectator/src/lib/base/base-spectator.ts
- projects/spectator/src/lib/spectator-http/create-factory.ts
- projects/spectator/src/lib/spectator-service/create-factory.ts
Backward compatibility change.
Allow to use 5.x lib version for Angular version less than v9.
Keep to use for Angular v9 as is.
```
[ ] Bugfix
[x] Feature
```
Issue Number: #283 
You can continue using the latest version of Spectator in you Angular projects with version less than 9 (e.g. 7, 8 etc.)
```
[ ] Yes
[x] No
```
> feat(lib): use TestBed.get if .inject falsy - back compatibility (#283)

- projects/spectator/src/lib/internals/rgb-to-hex.ts
- projects/spectator/src/lib/matchers.ts
Additional fix for #270 
```
[x] Bugfix
[ ] Feature
```
Throws error 'replace of null' in trim() function when jQuery.css() returns null in hasCss matcher.
Issue Number: #270
If jQuery.css() returns null pass empty string (`''`) to trim() function.
```
[ ] Yes
[x] No
```
> fix(rgb-to-hex): fix trim function to handle falsy value(#270)

- README.md
'styleext' changed to 'style'
- [ x ] The commit message follows our guidelines: https://github.com/ngneat/spectator/blob/master/CONTRIBUTING.md#commit
- [ N/A ] Tests for the changes have been added (for bug fixes / features)
- [ N/A ] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
[ x ] Documentation content changes
```
Incorrect documentation of using scss in schematics.
Corrected documentation.
```
[ ] Yes
[ x ] No
```
This syntax was changed …
> docs(schematics): syntax update

- README.md
- projects/spectator/jest/test/dom-selectors/dom-selectors.component.spec.ts
- projects/spectator/src/lib/dom-selectors.ts
- projects/spectator/test/dom-selectors/dom-selectors.component.spec.ts
- projects/spectator/test/dom-selectors/dom-selectors.component.ts
```
[ ] Bugfix
[x] Feature
```
Currently TS type for `byText` query doesn't allow to specify `selector` option however it's supported by the underlying `@testing-library/dom` module.
Added support for `selector` option.
```
[ ] Yes
[x] No
```
> feat(dom-selectors): add `selector` option to `byText` query

- README.md
- package-lock.json
- projects/spectator/jest/src/lib/dom-selectors.ts
- projects/spectator/jest/test/dom-selectors/dom-selectors.component.spec.ts
- projects/spectator/src/lib/dom-selectors.ts
- projects/spectator/test/dom-selectors/dom-selectors.component.spec.ts
- projects/spectator/test/dom-selectors/dom-selectors.component.ts
```
[ ] Bugfix
[x] Feature
[x] Other... Please describe: I've also updated Prettier to v1.19.1 in `package-lock.json` (this version still matches the version from `package.json`) because old version didn't support optional chaining operator which I use in this PR.
```
Current `byText` query matches text only in direct element's text nodes and doesn't support nested elements.
For example, `byText('foobar')` won't match `div` in this example:
```html
<div>
<span>foo</span><span>bar</span>
</div>
``` …
> feat(dom-selectors): add `byTextContent` query

- README.md
- projects/spectator/src/lib/base/dom-spectator.ts
- projects/spectator/src/lib/dispatch-events.ts
- projects/spectator/src/lib/internals/event-objects.ts
- projects/spectator/src/lib/internals/key-parser.ts
- projects/spectator/src/lib/types.ts
- projects/spectator/test/events/events.component.html
- projects/spectator/test/events/events.component.spec.ts
- projects/spectator/test/events/events.component.ts
```
[ ] Bugfix
[X] Feature
```
Issue Number: 278
DomSpectator keyboard events now accept an object with key and keyCode as parameters.
```
[ ] Yes
[X] No
```
> feat: add key & keyCode parameter for keyboard events

- package-lock.json
- package.json
- projects/spectator/ng-package.json
- projects/spectator/package.json
- projects/spectator/schematics/package.json
Schematics-utilities package was introduced in 6d74f4f022586794a80281082c93e8252fb5d72a
Usages of this package was removed in 372f848448fd384d04d50d1314736c34e81bd832
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #292 
schematics-utilities removed from dependencies list
```
[ ] Yes
[x] No
```
> fix(schematics): get rid of schematics-utilities

- package-lock.json
- package.json
```
[ ] Bugfix
[ ] Feature
[x ] Other... Please describe: security fix
```
jQuery updated to 3.5.0 to mitigate https://github.com/advisories/GHSA-gxr4-xjj5-5px2
```
[ ] Yes
[x] No
```
> fix: update jquery to 3.5.0 to mitigate xss attack

- docs/docs/testing-directives.md
- docs/docs/testing-pipes.md
- docs/docs/testing-with-host.md
- projects/spectator/jest/src/lib/spectator-directive.ts
- projects/spectator/jest/src/lib/spectator-host.ts
- projects/spectator/src/lib/spectator-directive/create-factory.ts
- projects/spectator/src/lib/spectator-host/create-factory.ts
- projects/spectator/src/lib/spectator-pipe/create-factory.ts
- projects/spectator/test/directive-providers.directive.spec.ts
- projects/spectator/test/pipe/alternating-sum.pipe.spec.ts
- projects/spectator/test/pipe/alternating-sum.pipe.ts
- projects/spectator/test/pipe/stats.service.ts
- projects/spectator/test/zippy/zippy.component.spec.ts
```
[ ] Bugfix
[x] Feature
```
The `template` parameter that can be passed to `createDirectiveFactory`, `createHostFactory`, and `createPipeFactory` is ignored.
Issue Number: #299 
Said `template` parameter is used as default when no template is explicitly passed to the factory. Typings have been updated, so that factories that were created with a default template can be called without passing an additional, explicit template.
```
[ ] Yes
[x] No
```
Really cool …
> feat: support passing template in factory (#299)

- README.md
- docs/docs/testing-components.md
- projects/spectator/jest/test/override-module.spec.ts
- projects/spectator/src/lib/base/options.ts
- projects/spectator/src/lib/spectator-directive/create-factory.ts
- projects/spectator/src/lib/spectator-host/create-factory.ts
- projects/spectator/src/lib/spectator-http/create-factory.ts
- projects/spectator/src/lib/spectator-pipe/create-factory.ts
- projects/spectator/src/lib/spectator-routing/create-factory.ts
- projects/spectator/src/lib/spectator-service/create-factory.ts
- projects/spectator/src/lib/spectator/create-factory.ts
- projects/spectator/test/override-module.spec.ts
```
[ ] Bugfix
[x] Feature
```
There is no override module feature.
Issue Number: #302
This commit adds override modules options to BaseSpectatorOptions. All
factories can get this options.
Example:
```typescript
createComponentFactory({
component: SomeComponent,
overrideModules: [
[SomeModule, {set: {declarations: [SomeOtherComponent]}],
[SomeOtherModule, {set: {declarations: [SomeOtherComponent]}]
]
})
```
```
[ ] Yes
[x] No
```
> feat: 🎸 support for overriding modules (#302)

- projects/spectator/jest/src/lib/mock.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #316
`createSpyObject` is public api also for Jest.
```
[ ] Yes
[x] No
```
> fix: make createSpyObject public (#316)

- README.md
- projects/spectator/jest/test/click/click.component.spec.ts
- projects/spectator/src/lib/base/dom-spectator.ts
- projects/spectator/src/lib/types.ts
- projects/spectator/test/calc/calc.component.spec.ts
- projects/spectator/test/calc/calc.component.ts
```
[ ] Bugfix
[x] Feature
```
Add support of DOMSelector shorthand in Events API
Before DOMSelectors should be wrapper in a query function `spectator.click(spectator.query(byText('Submit')))` and with this changes it can be used in shorthand format ``spectator.click(byText('Submit'))``
```
[ ] Yes
[x] No
```
> feature:🎸 Support DOMSelectors shorthands in Events api

- package-lock.json
- package.json
- projects/spectator/package.json
allows to use spectator 5.x with Angular 8 with TS 3.5
Signed-off-by: Andrey Chalkin <L2jLiga@gmail.com>
```
[ ] Bugfix
[x] Feature
[x] Build related changes
```
Angular 8 with TS 3.5 tests fails due to TS errors like
```
node_modules/@ngneat/spectator/lib/spectator/spectator.d.ts:15:9 - error TS1086: An accessor cannot be declared in an ambient context.
15    get component(): C;
```
`.d.ts` are downleveled to build without any errors
`get component(): C;` -> `readonly …
> feat: downlevel .d.ts for older TS versions

- projects/spectator/jest/src/lib/spectator-directive.ts
- projects/spectator/jest/src/lib/spectator-host.ts
- projects/spectator/jest/src/lib/spectator-http.ts
- projects/spectator/jest/src/lib/spectator-routing.ts
- projects/spectator/jest/src/lib/spectator.ts
- projects/spectator/src/lib/core.ts
- projects/spectator/src/lib/matchers.ts
- projects/spectator/src/lib/spectator-directive/create-factory.ts
- projects/spectator/src/lib/spectator-host/create-factory.ts
- projects/spectator/src/lib/spectator-pipe/create-factory.ts
- projects/spectator/src/lib/spectator-routing/create-factory.ts
- projects/spectator/src/lib/spectator/create-factory.ts
- projects/spectator/test/form-select/form-select.component.spec.ts
Created generic `addMatchers` function which will handle Jasmine vs Jest ways
Signed-off-by: Andrey Chalkin <L2jLiga@gmail.com>
```
[ ] Bugfix
[x] Feature
```
Issue Number: #314 
Use [`expect.extend`]() from Jest to add custom matchers.
```
[ ] Yes
[x] No
```
> feat: support jest-circus

- README.md
- projects/spectator/src/lib/spectator-routing/activated-route-stub.ts
- projects/spectator/src/lib/spectator-routing/create-factory.ts
- projects/spectator/src/lib/spectator-routing/options.ts
- projects/spectator/src/lib/spectator-routing/route-options.ts
- projects/spectator/src/lib/spectator-routing/spectator-routing.ts
- projects/spectator/test/with-routing/my-page.component.spec.ts
- projects/spectator/test/with-routing/my-page.component.ts
add optional url property to route options
update readme with new url property
```
[ ] Bugfix
[x] Feature
```
ActivatedRoute currently doesn't have a `url` property causing an error if you have references to `ActivatedRoute.url` in your code
Issue Number: #323 
Add optional `url` property that accepts `UrlSegment[]` to `routeOption` 
```
[ ] Yes
[x] No
```
> feat(routing): add support for ActivatedRoute url property

- README.md
Add hint about order of defineGlobalsInjections and fix typo in import. This is addressing #332
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: update README on defineGlobalsInjections

- projects/spectator/src/lib/spectator-routing/create-factory.ts
- projects/spectator/test/with-routing/my-page.component.spec.ts
wrap createSpectatorRouting in ngZone
run `router.navigate` in spec file in ngZone
```
[x] Bugfix
[ ] Feature
```
Navigation causes the following warning:
`WARN: 'Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?'`
Issue Number: #298 
No more warnings by wrapping navigation related functionality in Angular zone.
```
[ ] Yes
[x] No
```
> fix(routing): fix 'Navigation triggered outside Angular Zone' warning

- projects/spectator/karma.conf.js
- projects/spectator/src/lib/mock.ts
```
[**X**] Bugfix
[ ] Feature
```
Running karma-jasmine tests under the project (ng10, es2015) will cause failure when trying to use
spyOnProperty() with the service previously mocked by spectator. It's very hard-to-trace issue we ran into.
```
Failed: <spyOnProperty> : "xxx" is not declared configurable
```
jasmine spyOnProperty fails when trying to mock properties which weren't declared as configurable
```
Object.defineProperty(mock, key, {
set: value => …
```
> Make installProtoMethods function declare properties configurable

- projects/spectator/src/lib/spectator-routing/activated-route-stub.ts
- projects/spectator/test/spectator-routing/activated-route-stub.spec.ts
Due to a breaking change in Typescript 4 a property could not be overwritten with an accessor
In the ActivatedRouteStub the snapshow property was overwritten with an get accessor
```
[x] Bugfix
[ ] Feature
```
In Angular Version 10.1 with Typescript 4 the production build fails because there is a breaking change which prevents overwriting a property with an accessor.
Issue Number: 345
The Snapshot in ActivatedRouteStub is now a field and no longer a get accessor. The …
> fix: change accessor to property in ActivatedRouteStub

- projects/spectator/schematics/src/spectator/files/component-host/__name@dasherize__.component.spec.ts
- projects/spectator/schematics/src/spectator/files/data-service/__name@dasherize__.service.spec.ts
was declaring spectator but using host
```
[x] Bugfix
[ ] Feature
```
component-host schematics was declaring spectator but using host
just fix that detail
```
[ ] Yes
[x] No
```
I believe that contributing can be more friendly, let's make it more explanatory about the flow.
I had to use --no-verify on the commit, because the schematics don't use the .template suffix, I didn't find which tests are testing which schematics / service. if someone helps …
> fix(component-host): setting for wrong variable

- README.md
- projects/spectator/src/lib/base/dom-spectator.ts
- projects/spectator/src/lib/internals/query.ts
- projects/spectator/src/lib/spectator-directive/spectator-directive.ts
- projects/spectator/src/lib/spectator-host/spectator-host.ts
- projects/spectator/src/lib/spectator-pipe/spectator-pipe.ts
- projects/spectator/test/simple-changes/simple-changes.component.spec.ts
- projects/spectator/test/simple-changes/simple-changes.component.ts
```
[ ] Bugfix
[x] Feature
```
When setting input bingins via `createComponentFactory(TestComponent)({ props: {} })` or  run `spectator.setInput(...)`, hook `ngOnChanges` is not called.
Issue Number: #348
The hook `ngOnChanges` fired on first install input's and update via `spectator.setInput()`, `spectator.setHostInput()`
```
[x] Yes
[ ] No
```
Now, internal `setProps` update value of instance only if values not equals. It is affected `setInput`, `setHostInput`.
> feat: support run ngOnChanges hook for change bingins (#348)

- projects/spectator/src/lib/internals/query.ts
- projects/spectator/test/set-input/set-input.component.spec.ts
- projects/spectator/test/set-input/set-input.component.ts
```
[x] Bugfix
[ ] Feature
```
`setInput` not update instance value if equals previous and new value. It's not work with only setter `Input`
Issue Number: 367
`setInput` update instance values always.
```
[ ] Yes
[x] No
```
> Fix update values via setInput

- vscode-snippets/README.md
- vscode-snippets/snippets/snippets.json
```
[ ] Bugfix
[x] Feature
```
VSCode snippets are only compatible with Jasmine (import from '@ngneat/spectator')
Issue Number: #404 
New snippets like `spec-jest-comp` are added, which will import from ('@ngneat/spectator/jest'')
```
[ ] Yes
[x] No
```
I have suggested snippets like `spec-XXX-jest` in #404 , but in this PR I use `spec-jest-XXX`, because that might be less annoying for current ('spec-XXX') users on auto completion.
> feat: add VSCode snippets for jest

- projects/spectator/package.json
Hmmm well, this is the reason I'm adding `lerna` + `yarn workspaces` to my NX and NG CLI repos...
the dependency management gets easier. WDYT of giving it a try @NetanelBasal?
> build: update package dependencies

- projects/spectator/schematics/src/spectator/files/component-host/__name@dasherize__.component.spec.ts
```
[ ] Bugfix
[x] Feature
```
The current test file generated for a component when using the `--with-host` flag uses a placeholder `zippy` selector rather than the actual selector for the new component (e.g. `createHost('<zippy title="Zippy title"></zippy>')` in the test file).
This updates the schematic to instead use the actual selector for the component instead, saving the step of having to update the selector used. So, `createHost('<zippy …
> feat(schematics): use actual component name in test file

- README.md
- docs/docs/events.md
- package.json
- projects/spectator/package.json
- projects/spectator/src/lib/base/dom-spectator.ts
- projects/spectator/test/overlay-custom-event/overlay-container.component.spec.ts
- projects/spectator/test/overlay-custom-event/overlay-container.component.ts
- projects/spectator/test/overlay-custom-event/overlay-container.module.ts
- projects/spectator/test/overlay-custom-event/overlay-content.component.ts
- yarn.lock
fix: adding a root option to trigger event handler method
TriggerEventHandler method currently doesn't support a search from root. Some angular components can create overlay elements which are part of the root and so, are not descendants of the current test dom element.
This change adds the support for finding the trigger component from the root. For this we are traversing up the DebugElement tree using the parent property. It is still a bounded search since the tree traversal will end at the root. Happy to explore other better approaches.
```
[X] Bugfix
[ ] Feature
[ ] Build …
```
> Trigger event handler

- projects/spectator/src/lib/spectator-host/create-factory.ts
Refactoring of createHostFactory to defer TestBed instantiation.  This also allows for use of Angular's spec injection functionality.
```
[ ] Bugfix
[x] Feature
```
Issue Number: 443
[Support spec injection when testing with a host component](https://github.com/ngneat/spectator/issues/443)
`template` option can be passed to `createHostFactory ` and then omitted from `spectatorHostFactory`.  This allows for instantiation of TestBed prior to the call to …
> feature(createHostFactory): PR for issue #443

- docs/docs/testing-with-http.md
```
[ ] Bugfix
[ ] Feature
```
The example missed the required `SpectatorHttp` import.
The documentation will show all required imports in the example
```
[ ] Yes
[x] No
```
> docs(testing-with-http): add missing import in example

- README.md
```
[ ] Bugfix
[ ] Feature
```
I ran into the same issue that another user of specator encountered where service dependencies used in OnInit are not initialized because detectChanges runs before the dependencies are injected.
Issue Number: #308
Simply documenting how to properly write the test so that less users struggle with this.
```
[ ] Yes
[ x] No
```
> docs(oninit-lifecycle-tests): mocked services in OnInit

- README.md
- docs/docs/events.md
Closes: #477
```
[ ] Bugfix
[ ] Feature
```
Issue Number: 477
```
[ ] Yes
[x] No
```
> docs: clarified limitation of blur()

- projects/spectator/src/lib/event-creators.ts
- projects/spectator/test/events/events.component.html
- projects/spectator/test/events/events.component.spec.ts
- projects/spectator/test/events/events.component.ts
```
[x] Bugfix
[ ] Feature
```
**code** property, which is favored over deprecated **keyCode** is not added to KeyboardEvent
Issue Number: #501 
**code** property is added to KeyboardEvent
```
[ ] Yes
[x] No
```
> fix: add code to KeyboardEvent

- projects/spectator/jest/test/dom-selectors/dom-selectors.component.spec.ts
- projects/spectator/package.json
- projects/spectator/src/lib/dom-selectors.ts
- projects/spectator/test/dom-selectors/dom-selectors.component.spec.ts
- projects/spectator/test/dom-selectors/dom-selectors.component.ts
- yarn.lock
API change while updating to new @testing-library/dom
fixes: #519
```
[x ] Bugfix
[x ] Feature
```
Issue Number: #519
Karma tests run without failure.
And: Matchers can now be numbers - a number matcher just matches number text, so the behavior is the same as if the matcher were `numberMatcher.toString()`. Because the change to the `Matcher` signature comes along with the dependency update required by this fix, the bug fix and exciting new feature come together.
```
[ …
```
> fix(startup error): update @testing-library/dom to update pretty-format

- projects/spectator/jest/test/matchers/matchers.spec.ts
- projects/spectator/src/lib/matchers.ts
```
[x] Bugfix
[x] Feature
```
Currently `toHaveStyle` doesn't detect CSS variables as they seem indexed by numbers:
The matcher now is able to `pass` raw values for CSS variables.
```
[ ] Yes
[x] No
```
Can this be cherry-picked and released in the `v8` branch please?
We're using Angular 12 and still using that version.
> fix(matchers): test css variables via getPropertyValue

- projects/spectator/src/lib/matchers.ts
- projects/spectator/tsconfig.lib.json
Hey Netanel.
I've been facing issues with `fakeAsync` and spectator during a long time, but I was thinking we're doing something wrong in unit tests. The issue has been happening so randomly, like in 1 of 10 cases, so I couldn't capture it. The tests were basically failing with `1 timer(s) still in the queue.`. So after debugging zone.js `onScheduleTask` I've found that the task, which is being scheduled, is `$.ready`.
See the code:
https://github.com/jquery/jquery/blob/5d5ea015114092c157311c4948f7cc3d8c8e7f8a/src/core/ready.js#L64-L70
I don't know if there's any other way to fix that issue and to force jquery **not** to schedule a timer. So I just unpatched the `setTimeout` before requiring jquery and then reset it back.
> fix: unpatch `setTimeout` before importing jQuery so it is not captured by zone.js

- README.md
- docs/docs/custom-matchers.md
- projects/spectator/jest/src/lib/matchers-types.ts
- projects/spectator/src/lib/matchers-types.ts
- projects/spectator/src/lib/matchers.ts
- projects/spectator/test/matchers/matcher-enhancements.component.spec.ts
- projects/spectator/test/matchers/matcher-enhancements.component.ts
```
[ ] Bugfix
[x] Feature
```
Users have to write:
```typescript
expect('.checkbox').toHaveProperty('indeterminate', true);
```
Users will be able to write:
```typescript
expect('.checkbox').toBeIndeterminate();
```
```
[ ] Yes
[x] No
```
> feat(matchers): add toBeIndeterminate matcher

- projects/spectator/src/lib/matchers.ts
```
[x] Bugfix
[ ] Feature
```
Matchers with `exact` argument have double spaces in their messages.
Messages without "typos".
```
[ ] Yes
[x] No
```
There were no tests, verifying the error messages. If you find it necessary I can add them, otherwise this is a rather simple PR.
> (fix): remove double space in matchers' messages

- projects/spectator/jest/test/query-root/query-root.component.spec.ts
- projects/spectator/src/lib/base/dom-spectator.ts
- projects/spectator/test/query-root/query-root.component.spec.ts
- projects/spectator/test/query-root/query-root.component.ts
```
[ ] Bugfix
[x] Feature
```
When using `spectator.query()`, you can use `{ root: true }` in order to query an element inside an overlay. But what if you want to query a `SomeModalContentComponent` inside an overlay ?
You cannot do `spectator.query(SomeModalContentComponent, { root: true })`.
Issue Number: 0
You can now query for components in a global way with `spectator.query(SomeModalContentComponent, { root: true })`.
```
[ ] Yes
[x] No
```
> feat(dom-spectator): add query with root opt for Type selector

- projects/spectator/jest/test/matchers/matchers.spec.ts
- projects/spectator/src/lib/matchers.ts
- N/A Docs have been added / updated (for bug fixes / features)
```
[x] Bugfix
[ ] Feature
```
When passing an element within a shadow dom into toBeVisible/toBeHidden, it is possible that the element which causes that element to be hidden is outside the shadow dom containing the element; in that case, it will crash with this error when it attempts to call getClientRects on the Shadow DOM node (which is a DocumentFragment, not an Element):
```
TypeError: …
```
> fix(matchers): prevent crash on elements in a Shadow DOM

- docs/docs/global-injections.md
- docs/docs/testing-components.md
- projects/spectator/src/lib/base/initial-module.ts
- projects/spectator/src/lib/base/options.ts
- projects/spectator/src/lib/spectator/options.ts
- projects/spectator/test/error-unknown/error-unknown-element.component.spec.ts
- projects/spectator/test/error-unknown/error-unknown-element.component.ts
- projects/spectator/test/error-unknown/error-unknown-property.component.spec.ts
- projects/spectator/test/error-unknown/error-unknown-property.component.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: https://github.com/ngneat/spectator/issues/575
When unknown elements or properties are used, it is just logged to stdout.
Allows failing test when unknown elements or properties are used
```
[ ] Yes
[x] No
```
> feat: allow erroring on unknown elements/properties

- projects/spectator/src/lib/dom-selectors.ts
Add proper typings to `byRole` to get role autocomplete
```
[x] Bugfix
[ ] Feature
```
Issue Number: #589 
Updated the `byRole` typings to provide role autocomplete.
```
[ ] Yes
[x] No
```
> fix(dom-selectors): `byRole` typings

- README.md
- projects/spectator/jest/src/lib/matchers-types.ts
- projects/spectator/jest/test/hello/hello.component.spec.ts
- projects/spectator/src/lib/matchers-types.ts
- projects/spectator/src/lib/matchers.ts
- projects/spectator/test/hello/hello.component.spec.ts
- projects/spectator/test/hello/hello.component.ts
- projects/spectator/test/matchers/matcher-enhancements.component.spec.ts
- projects/spectator/test/matchers/matcher-enhancements.component.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #568 
- `toHaveExactText` matcher accepts a second parameter that allows to trim actual text value before being checked, e.g. `    expect(element).toHaveExactText('some text', true);`
- `toHaveExactTrimmedText` matcher is added as a convenient shorthand for the above
```
[ ] Yes
[x] No
```
> feat(matchers): add toHaveExactTrimmedText matcher

- .husky/commit-msg
- .husky/pre-commit
- package.json
- yarn.lock
- fix git commit message linting
- fix lint-staged (lint .ts files on commit)
- Update husky and fixed `git commit-msg hook` to make sure commits follow project's conventional commits
- Update lint-staged and fixed `git pre-commit hook` to automatically format code with prettier upon git commit
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
```
[ ] Yes
[x] No
```
`yarn format` hasn't been run for a while.
Currently it'll format `133` files.
I can include the lint fixes in this PR to prevent noisy code diffs in …
> ci: 🎡 update husky, lint-staged and commitlint

- package.json
- yarn.lock
- remove transitive jest@28 and ts-jest@28 dependencies from yarn.lock
- fix ts-jest warnings in console when running "yarn test:jest"
```shell
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
<transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
```
```
[ ] Bugfix
[ ] Feature
```
console is full of warnings:
jest28 is still installed:
No more warnings in …
> ci: 🎡 align jest v29 dependencies

- projects/spectator/jest/test/matchers/matchers.spec.ts
- projects/spectator/src/lib/matchers.ts
```
[x] Bugfix
[ ] Feature
```
Currently, .toBeHidden cannot catch cases where an element is hidden through CSS, be it a separate style element, constructed stylesheets, or just CSS variables in the `style` attribute. This change should catch all of those cases.
Elements hidden with separate style element, constructed stylesheets, or CSS variables are now correctly determined to be hidden
```
[ ] Yes
[x] No
```
This test contains a breaking change in …
> fix(matchers): use computed styles to determine hidden-ness

- projects/spectator/src/lib/spectator-host/host-component.ts
```
[x] Bugfix
[ ] Feature
```
Running tests with Spectator `15.0.1` inside the latest Nx (`16.6.0`) it is throwing this warning:
```
NG0912: Component ID generation collision detected. Components '_HostComponent' and 'TestComponent'
with selector 'ng-component' generated the same component ID. To fix this, you can change the selector
of one of those components or add an extra host attribute to force a different ID.
Find more at https://angular.io/errors/NG0912
```
I …
> fix: 🐛 component-id collision error NG0912

- projects/spectator/package.json
Updated jQuery package to the next non-vulnerable version (3.6.4) as per this https://security.snyk.io/package/npm/jquery/3.6.0
```
[x] Bugfix
[ ] Feature
```
The currentSpectator version is released with a jQuery 3.6.0 dependency which has a security vulnerability.
This PR updates the package.json that is used for release to fix the vulnerability.
```
[ ] Yes
[x] No
```
> fix(spectator): updated jQuery package to 3.6.4

- docs/docs/queries.md
```
[ ] Bugfix
[ ] Feature
```
It is missing the `byRole` example from the [readme](https://github.com/ngneat/spectator?tab=readme-ov-file#dom-selector)
Add the `byRole` example
```
[ ] Yes
[x] No
```
> doc(queries): add missing byRole example

- README.md
- projects/spectator/jest/test/defer-block.spec.ts
- projects/spectator/src/lib/base/initial-module.ts
- projects/spectator/src/lib/base/options.ts
- projects/spectator/src/lib/spectator/spectator.ts
- projects/spectator/src/lib/types.ts
- projects/spectator/test/defer-block.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(spectator): support defer block behavior

- projects/spectator/jest/test/ngonchanges-input/ngonchanges-input.component.spec.ts
- projects/spectator/src/lib/spectator/spectator.ts
- projects/spectator/test/matchers/matcher-enhancements.component.spec.ts
- projects/spectator/test/ngonchanges-input/ngonchanges-input.component.spec.ts
- projects/spectator/test/ngonchanges-input/ngonchanges-input.component.ts
- projects/spectator/test/standalone/pipe/standalone.pipe.spec.ts
```
[X] Bugfix
[ ] Feature
```
See #643
When Spectator is used to set inputs on a component, the following will happen:
1. `ChangeDetectorRef.detectChanges()` is called
2. `fixture.detectChanges` is called
Issue Number: #643 
I simply swapped these 2 calls:
1. `fixture.detectChanges` will run a change detection cycle on the test fixture. This is when `ngOnChanges` will run
2. `ChangeDetectorRef.detectChanges()` will check the component view. This is where the change …
> fix: 🐛 component re-render when updating fields in lifecycle hook

- projects/spectator/jest/src/lib/matchers-types.ts
This better aligns with jest documentation: https://archive.jestjs.io/docs/en/23.x/expect#expectextendmatchers and ensures that types can work properly with other jest extension libraries like jest-chain.
```
[x] Bugfix
[ ] Feature
```
Currently, when another library is used that modifies the return type of a matcher, all custom matchers added by spectator cannot be overridden in TypeScript because they do not use the `R` generic. This fixes that problem.
Issue Number: …
> chore: 🏷️ Use generic return type for all jest matchers

- .github/workflows/ci.yml
- run on `ubuntu-latest`
- upgrade `github actions` to `v4`
```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
Deprecation warning messages in github action builds:
> ⚠️ Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2, actions/cache@v2.
- https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20
- https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
Build …
> ci: 🎡 upgrade github actions to v4

- projects/spectator/jest/test/function-output/function-output.component.spec.ts
- projects/spectator/src/lib/base/dom-spectator.ts
- projects/spectator/test/function-output/function-output.component.spec.ts
- projects/spectator/test/function-output/function-output.component.ts
```
[ ] Bugfix
[x] Feature
```
currently there are a couple of issues with `spectator.output`
1. Unless you add a specific return type then it returns an `Observable<unknown>` 
2. Doesn't support function based outputs (https://angular.dev/guide/components/output-fn#)
1. Added 2 additional overloads for the `output` method
-  one very similar to the existing one but with the return type `OutputEmitterRef<T>`
-  one that infers the return type based on the key name.
2. …
> feat(spectator): support for Function-based outputs

- docs/docs/testing-with-http.md
```
[ ] Bugfix
[ ] Feature
```
The interface for HttpExpect has a lowercase `url` where the documentation uses `URL`:
```ts
export interface HttpExpect {
url: string;
method: HttpMethod;
}
```
Updated the documentation to use the right property
```
[ ] Yes
[x] No
```
> docs: update typo in http testing example

- README.md
- projects/spectator/jest/src/lib/spectator-injection-context.ts
- projects/spectator/jest/src/public_api.ts
- projects/spectator/jest/test/run-in-injection-context.spec.ts
- projects/spectator/src/lib/base/base-spectator.ts
- projects/spectator/src/lib/spectator-injection-context/create-factory.ts
- projects/spectator/src/lib/spectator-injection-context/initial-module.ts
- projects/spectator/src/lib/spectator-injection-context/options.ts
- projects/spectator/src/lib/spectator-injection-context/spectator-injection-context.ts
- projects/spectator/src/lib/types.ts
- projects/spectator/src/public_api.ts
- projects/spectator/test/run-in-injection-context.spec.ts
- projects/spectator/vitest/src/lib/spectator-injection-context.ts
- projects/spectator/vitest/src/public_api.ts
- projects/spectator/vitest/test/run-in-injection-context.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #664 
There is no support for `runInInjectionContext()` in Spectator
- Each Spectator instance offers access to `runInInjectionContext()`
- New `createInjectionContextFactory` is included for easy DI Functions testing
```
[ ] Yes
[x] No
```
> feat(spectator): add support for runInInjectionContext()

- projects/spectator/jest/test/set-input-alias-names.spec.ts
- projects/spectator/src/lib/spectator/spectator.ts
- projects/spectator/test/set-input-alias-names.spec.ts
- projects/spectator/vitest/test/set-input-alias-names.spec.ts
```
[X] Bugfix
[ ] Feature
```
Cannot compile test when we call setInput on more than one input whose one is aliased (object parameter)
Issue Number: https://github.com/ngneat/spectator/issues/691
We can compile and execute test when we call setInput on more than one input whose one is aliased (object parameter)
```
[ ] Yes
[X] No
```
> fix(spectator): setInput with object parameter for alias names (#691)

- projects/spectator/jest/test/function-output/function-output.component.spec.ts
- projects/spectator/src/lib/base/dom-spectator.ts
- projects/spectator/test/function-output/function-output.component.spec.ts
- projects/spectator/test/function-output/function-output.component.ts
Allow subjects as component output
✅ Closes: #689
```
[X] Bugfix
[ ] Feature
```
Issue Number: #689 
```
[ ] Yes
[X] No
```
> fix: 🐛 type check on component outputs

- README.md
- docs/docs/testing-components.md
- projects/spectator/src/lib/spectator-host/create-factory.ts
- projects/spectator/src/lib/spectator/create-factory.ts
- projects/spectator/src/lib/spectator/options.ts
- projects/spectator/test/standalone/component/standalone-with-imports.component.spec.ts
- projects/spectator/test/standalone/component/standalone-with-imports.component.ts
```
[ ] Bugfix
[x] Feature
```
To override the tested component's imports, the 'overrideComponents' option can be used. This works but is not very intuitive and involves a relatively complex configuration.
Add 'componentImports' config option override the tested component's imports to allow for overrides of the tested component's imports. This config option is supported by createComponentFactory as well as createHostFactory.
```
[ ] Yes
[x] No
``` …
> feat: add support for componentImports config

- projects/spectator/vite.config.mts
- projects/spectator/vitest/test/highlight.directive.spec.ts
- projects/spectator/vitest/test/zippy/zippy.component.spec.ts
```
[x] Bugfix
[ ] Feature
[x] CI related changes
```
Running Vitest specs locally works fine; however, during ci, the specs fail with message "Segmentation fault"
Running all tests locally works.
```
[ ] Yes
[x] No
```
Set `pool` config property to 'forks' in vite config as suggested here: https://github.com/vitest-dev/vitest/issues/3143. In addition, add definitions for window in tests that depend on window.
> test: set pool prop in vite config

- docs/docs/queries.md
- projects/spectator/jest/test/matchers/matchers.spec.ts
- projects/spectator/src/lib/matchers.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #541 
Adds direct support within the custom matchers to calculate DOM Selectors
```
[ ] Yes
[x] No
```
> Allow Direct Usage of DOMSelector Instances in Custom Matchers

- projects/spectator/src/lib/spectator-directive/create-factory.ts
- projects/spectator/src/lib/spectator-host/create-factory.ts
- projects/spectator/src/lib/spectator-pipe/create-factory.ts
- projects/spectator/src/lib/spectator-routing/create-factory.ts
- projects/spectator/src/lib/spectator/create-factory.ts
In this commit, we remove `waitForAsync` as it is no longer necessary. This rule has also been disabled internally at Google and is no longer in use. Its removal enables zoneless support, since `waitForAsync` depends on zone.js.
We also remove `compileComponents()`, as it is only required when `setClassMetadataAsync` is called—typically representing AOT pre-compiled components outside of TestBed.
> fix: remove `waitForAsync` (zoneless support)

- package.json
- yarn.lock
caused by `rollup-plugin-dts` in `ng-packagr` v20: https://github.com/ng-packagr/ng-packagr/issues/3085
downgrading `ng-packagr` to v19 fixes the issue, which doesn't use `rollup-plugin-dts`
✅ Closes: #712
```
[x] Bugfix
[ ] Feature
```
jasmine custom matchers are broken
fix jasmine custom matchers
```
[ ] Yes
[x] No
```
> fix: 🐛 jasmine customer matchers

- projects/spectator/jest/test/defer-block.spec.ts
- projects/spectator/setup-jest.ts
- projects/spectator/test/standalone/component/standalone-with-imports.component.ts
fix terminal console warnings and errors when running tests:
- fix `jest` "ERROR ReferenceError: IntersectionObserver is not defined" 
- Use same mock from `vitest`: https://github.com/ngneat/spectator/blob/691c476e7108eb556c47cab1f449b2f4687ebb23/projects/spectator/setup-vitest.ts#L17-L25
- fix NG0912: Component ID generation collision detected (https://angular.dev/errors/NG0912)
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
```
[ ] Yes
[x] No
```
> chore: 🤖 fix clutter in test terminal output

- docs/docs/queries.md
- projects/spectator/jest/test/dom-selectors/dom-selectors.component.spec.ts
- projects/spectator/test/dom-selectors/dom-selectors.component.spec.ts
- projects/spectator/test/dom-selectors/dom-selectors.component.ts
- projects/spectator/vitest/test/dom-selectors/dom-selectors.component.spec.ts
✅ fixes: #380
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Add missing `byTestId` unit tests
```
`byTestId` is not documented: https://ngneat.github.io/spectator/docs/queries#dom-selector
- Documented `byTestId`
- Document how to use `byTestId` with custom `testIdAttribute`
(https://testing-library.com/docs/queries/bytestid#overriding-data-testid)
- Add missing `byTestId` unit tests
- Updated `byTestId` documentation for AI assisted coding: https://context7.com/ngneat/spectator
```
[ ] …
```
> docs: ✏️ byTestId DOM selector

- README.md
- docs/docs/testing-components.md
- projects/spectator/jest/test/bindings/bindings.component.spec.ts
- projects/spectator/src/lib/spectator-routing/create-factory.ts
- projects/spectator/src/lib/spectator/create-factory.ts
- projects/spectator/src/lib/spectator/options.ts
- projects/spectator/test/bindings/bindings.component.spec.ts
- projects/spectator/test/bindings/bindings.component.ts
- projects/spectator/vitest/test/bindings/bindings.component.spec.ts
✅ fixes #728
```
[ ] Bugfix
[x] Feature
```
TestBed `bindings` not supported. (Introduced in https://github.com/angular/angular/pull/62040)
Support for TestBed native `bindings` option. (`inputBinding`, `outputBinding`, `twoWayBinding`)
This makes it easier to test components by avoiding the need to create a wrapper component.
Native alternative for `setInput`, `output`, `props`
```
[ ] Yes
[x] No
```
> feat: 🎸 support for bindings
